server:
  port: 8762

spring:
  application:
    name: user
  datasource:
    username: d_dev_rw
    password: Ymn2738#HwqBAo
    url: jdbc:mysql://10.1.1.176:3306/user_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    password: wtf
    sentinel:
      nodes: 10.1.1.232:17001,10.1.1.232:17002,10.1.1.232:17003
      master: mymaster
    pool:
      max-active: 300
      max-wait: -1
      max-idle: 100
      min-idle: 20
    database: 15
    timeout: 6000


