server:
  port: 8762

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-second: 5
    lease-expiration-duration-in-second: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: user
