server:
  port: 8762

#eureka:
#  instance:
#    hostname: localhost
#    lease-renewal-interval-in-second: 5
#    lease-expiration-duration-in-second: 10
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: user
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://127.0.0.1:3306/clound_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:/mybaits/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml